name: Build with charm tools

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Ubuntu series to use as the builder'
        default: "ubuntu-20.04"
        required: false
        type: string
      charmtools-channel:
        description: |
          snap channel for charm tools, installed via snap
        required: false
        default: 2.x/stable
        type: string
      layers-list:
        required: false
        default: 'https://raw.githubusercontent.com/charmed-kubernetes/jenkins/main/jobs/includes/charm-layer-list.inc'
        type: string
      layer-index:
        description: |
          URL of the reactive layer index
        default: 'https://charmed-kubernetes.github.io/layer-index/'
        type: string
      layer-branch:
        description: |
          Branch of the reactive layer index
        default: ''
        type: string
      project-dir:
        description: |
          Specify the project's directory
        default: './'
        type: string

jobs:
  charm-build:
    name: Charm Build
    runs-on: ${{ inputs.runs-on }}
    env:
      CHARM_LAYERS_DIR: cache/layers
      CHARM_INTERFACES_DIR: cache/interfaces
      LAYER_BRANCH: ${{ inputs.layer-branch }}
    steps:
      - name: Initialize Charm tools
        run: |
          sudo snap install charm --channel ${{ inputs.charmtools-channel }} --classic
          sudo snap install yq
          sudo apt update
          sudo apt install parallel -y

      - uses: actions/checkout@v3

      - name: Fetch branch layers and build
        id: metadata
        run: |
          mkdir -p $CHARM_LAYERS_DIR
          mkdir -p $CHARM_INTERFACES_DIR
          export LAYER_BRANCH=${LAYER_BRANCH:-$GITHUB_REF_NAME}
          curl ${{ inputs.layers-list }} | yq '.[] | keys | .[0]' | grep -v 'layer:index' | parallel -j 4 charm pull-source -i ${{ inputs.layer-index }} -b ${LAYER_BRANCH} {}
          charm build -r --force -i https://localhost --charm-file ${{ inputs.project-dir }}
          echo "NAME=$(yq '.name' metadata.yaml)" >> "$GITHUB_OUTPUT"

      - name: Upload charm artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.metadata.outputs.NAME }}
          path: ./*.charm
