name: Lint-Unit

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Which ubuntu series should be used for the runner'
        default: "ubuntu-24.04"
        required: false
        type: string
      python:
        description: 'Matrix of python versions formatted as a JSON array'
        default: "['3.8', '3.10', '3.12']"
        required: false
        type: string
      working-directory:
        description: 'Path to directory within repo where Lint and Unit should run'
        default: './'
        required: false
        type: string
      with-uv:
        description: 'Whether to run with tox-uv'
        default: false
        required: false
        type: boolean
  
jobs:
  lint-unit:
    name: Lint and Unit Tests
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        python: ${{ fromJson(inputs.python) }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Setup using Python
      - name: Setup Python
        uses: actions/setup-python@v5
        if: ${{ inputs.with-uv == false }}
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        if: ${{ inputs.with-uv == false }}
        run: pip install tox

      # Setup using UV
      - uses: astral-sh/setup-uv@v5
        if: ${{ inputs.with-uv == true }}
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox with UV
        if: ${{ inputs.with-uv == true }}
        run: uv tool install tox --with tox-uv

      - name: Lint
        run: tox -vve lint
      - name: Unit Tests
        run: tox -vve unit
