name: Python Pull Request Workflow

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8', '3.10', '3.12']
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Locate Pip
              run: which pip

            - name: Install dependencies
              run: pip install tox

            - name: Locate Tox
              run: which tox
